-- Datos de referencia: los 48 barrios de CABA y cuadrillas iniciales.

INSERT INTO barrio (id, nombre, nombre_normalizado) VALUES
    (gen_random_uuid(), 'Agronomía', 'agronomia'),
    (gen_random_uuid(), 'Almagro', 'almagro'),
    (gen_random_uuid(), 'Balvanera', 'balvanera'),
    (gen_random_uuid(), 'Barracas', 'barracas'),
    (gen_random_uuid(), 'Belgrano', 'belgrano'),
    (gen_random_uuid(), 'Boedo', 'boedo'),
    (gen_random_uuid(), 'Caballito', 'caballito'),
    (gen_random_uuid(), 'Chacarita', 'chacarita'),
    (gen_random_uuid(), 'Coghlan', 'coghlan'),
    (gen_random_uuid(), 'Colegiales', 'colegiales'),
    (gen_random_uuid(), 'Constitución', 'constitucion'),
    (gen_random_uuid(), 'Flores', 'flores'),
    (gen_random_uuid(), 'Floresta', 'floresta'),
    (gen_random_uuid(), 'La Boca', 'la boca'),
    (gen_random_uuid(), 'La Paternal', 'la paternal'),
    (gen_random_uuid(), 'Liniers', 'liniers'),
    (gen_random_uuid(), 'Mataderos', 'mataderos'),
    (gen_random_uuid(), 'Monte Castro', 'monte castro'),
    (gen_random_uuid(), 'Monserrat', 'monserrat'),
    (gen_random_uuid(), 'Nueva Pompeya', 'nueva pompeya'),
    (gen_random_uuid(), 'Núñez', 'nunez'),
    (gen_random_uuid(), 'Palermo', 'palermo'),
    (gen_random_uuid(), 'Parque Avellaneda', 'parque avellaneda'),
    (gen_random_uuid(), 'Parque Chacabuco', 'parque chacabuco'),
    (gen_random_uuid(), 'Parque Chas', 'parque chas'),
    (gen_random_uuid(), 'Parque Patricios', 'parque patricios'),
    (gen_random_uuid(), 'Puerto Madero', 'puerto madero'),
    (gen_random_uuid(), 'Recoleta', 'recoleta'),
    (gen_random_uuid(), 'Retiro', 'retiro'),
    (gen_random_uuid(), 'Saavedra', 'saavedra'),
    (gen_random_uuid(), 'San Cristóbal', 'san cristobal'),
    (gen_random_uuid(), 'San Nicolás', 'san nicolas'),
    (gen_random_uuid(), 'San Telmo', 'san telmo'),
    (gen_random_uuid(), 'Vélez Sarsfield', 'velez sarsfield'),
    (gen_random_uuid(), 'Versalles', 'versalles'),
    (gen_random_uuid(), 'Villa Crespo', 'villa crespo'),
    (gen_random_uuid(), 'Villa del Parque', 'villa del parque'),
    (gen_random_uuid(), 'Villa Devoto', 'villa devoto'),
    (gen_random_uuid(), 'Villa General Mitre', 'villa general mitre'),
    (gen_random_uuid(), 'Villa Lugano', 'villa lugano'),
    (gen_random_uuid(), 'Villa Luro', 'villa luro'),
    (gen_random_uuid(), 'Villa Ortúzar', 'villa ortuzar'),
    (gen_random_uuid(), 'Villa Pueyrredón', 'villa pueyrredon'),
    (gen_random_uuid(), 'Villa Real', 'villa real'),
    (gen_random_uuid(), 'Villa Riachuelo', 'villa riachuelo'),
    (gen_random_uuid(), 'Villa Santa Rita', 'villa santa rita'),
    (gen_random_uuid(), 'Villa Soldati', 'villa soldati'),
    (gen_random_uuid(), 'Villa Urquiza', 'villa urquiza');

INSERT INTO cuadrilla (id, nombre, especialidad, disponible) VALUES
    (gen_random_uuid(), 'Cuadrilla Electrica 1', 'CABLEADO', true),
    (gen_random_uuid(), 'Cuadrilla Electrica 2', 'CABLEADO', true),
    (gen_random_uuid(), 'Cuadrilla Vial 1', 'BACHEO', true),
    (gen_random_uuid(), 'Cuadrilla Vial 2', 'BACHEO', true),
    (gen_random_uuid(), 'Cuadrilla Alumbrado 1', 'ALUMBRADO', true),
    (gen_random_uuid(), 'Cuadrilla Arbolado 1', 'ARBOLADO', true),
    (gen_random_uuid(), 'Inspeccion Ruidos 1', 'RUIDOS_MOLESTOS', true);
